# Makefile for lab 9

CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = main.cpp buffer.cpp palindrome.cpp Menu.cpp

HEADERS = buffer.hpp palindrome.hpp Menu.hpp

OBJS = main.o buffer.o palindrome.o Menu.o

main: ${OBJS}
	${CXX} ${CXXFLAGS} ${OBJS} -o main

${OBJS}: ${SRCS}
	${CXX} ${CXXFLAGS} -c $(@:.o=.cpp)

clean:
	rm *.o main
