# Makefile for lab 6 

CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = main.cpp Queue.cpp QueueNode.cpp Menu.cpp

HEADERS = Queue.hpp QueueNode.hpp Menu.hpp

OBJS = main.o Queue.o QueueNode.o Menu.o

main: ${OBJS}
	${CXX} ${CXXFLAGS} ${OBJS} -o main

${OBJS}: ${SRCS}
	${CXX} ${CXXFLAGS} -c $(@:.o=.cpp)

clean:
	rm *.o main
